#!/bin/bash
# Check to see if running as root
echo -e "\nChecking for root."
if [ `id -u` != 0 ]; then
	echo ""
    echo "Not root."
	echo ""
    echo -e "Need to be run as root.\n"
	echo ""
    echo "Try 'sudo -s' then the script."
    echo ""
    exit 1
else
	echo ""
    echo "Root."
	echo ""
fi
# Kernel - save data to disk after getting 8 seconds old with 16MB buffer
cat <<EOF > /etc/sysctl.d/30-pc-optimizations.conf
vm.swappiness = 1
vm.min_free_kbytes = 32768
vm.vfs_cache_pressure = 300
vm.dirty_bytes = 16777216
vm.dirty_background_bytes = 16777216
vm.dirty_writeback_centisecs = 800
vm.dirty_expire_centisecs = 800
EOF
# Kernel - don't care about IPV6 at all, use only IPV4
cat <<EOF > /etc/sysctl.d/99-pc-disable-ipv6.conf
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
EOF
# Load all sysctl configuration files manually
sysctl --system
# Show the sysctl configurations to see if they look well
sysctl -a | grep disable | grep ipv6
# Disable blocking automatic updates
# https://unix.stackexchange.com/questions/315502/how-to-disable-apt-daily-service-on-ubuntu-cloud-vm-image
mv /usr/lib/apt/apt.systemd.daily /usr/lib/apt/apt.systemd.daily.DISABLED
cat <<EOF >> /etc/bash.bashrc
alias ydmax='youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4'
alias ydmed='youtube-dl -f mp4/best'
EOF
sync
sleep 1
reboot
