#!/bin/bash
# Check to see if running as root
echo -e "\nChecking for root."
if [ `id -u` != 0 ]; then
	echo ""
    echo "Not root."
	echo ""
    echo -e "Need to be run as root.\n"
	echo ""
    echo "Try 'sudo -s' then the script."
    echo ""
    exit 1
else
	echo ""
    echo "Root."
	echo ""
fi
# Kernel - save data to disk after getting 6 seconds old with 8MB buffer
cat <<EOF > /etc/sysctl.d/30-pc-optimizations.conf
vm.swappiness = 60
vm.min_free_kbytes = 8192
vm.vfs_cache_pressure = 500
vm.dirty_bytes = 8388608
vm.dirty_background_bytes = 8388608
vm.dirty_writeback_centisecs = 600
vm.dirty_expire_centisecs = 600
EOF
# Kernel - don't care about IPV6 at all, use only IPV4
cat <<EOF > /etc/sysctl.d/99-pc-disable-ipv6.conf
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
EOF
# Load all sysctl configuration files manually
sysctl --system
# Show the sysctl configurations to see if they look well
sysctl -a | grep disable | grep ipv6
apt-get update && apt-get upgrade -y
apt-get install -y mc ncdu file-roller unar mesa-vdpau-drivers mesa-va-drivers mpv git vdpauinfo vainfo mediainfo-gui mc ncdu iotop youtube-dl smartmontools opensssh-server fluid-soundfont-gm fluid-soundfont-gs audacious gcc-avr avrdude avr-libc usb-creator-gtk dpkg-dev wine-development winetricks
cat <<EOF >> /etc/bash.bashrc
alias ydmax='youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4'
alias ydmed='youtube-dl -f mp4/best'
EOF
sync
sleep 1
reboot
